### ISSUE TITLE
Add eslint?

### ISSUE THREAD

**Issue by Rosey** [draft-js-plugins/next#8]
I am sure this is on your radar! Just noticed a few missing semicolons and was considering copying the eslint rules from the original draft-js-plugins in a PR but didn't want to overstep in case you already have plans in place for this.

Edit: I guess based on your current package.json you've been using `react-scripts` and there's a (long-running... 😬) PR open to add the lint as an option too https://github.com/facebook/create-react-app/pull/3850

**Comment by juliankrispel** [comment]
Absolutely ❤️, this is fixed now thanks for raising it. I've added both prettier and eslint as well as husky for commit hooks and travis for CI. I'll add a bunch of issues shortly to make sure there's enough stuff people can pick up.

Thanks so much again for getting involved @Rosey.
